import React, { useState } from 'react';
import axios from 'axios';
import '../css/ColdEmailForm.css';

const ColdEmailForm = () => {
  const [file, setFile] = useState(null);
  const [inputs, setInputs] = useState({ 
    email: '', 
    password: '', 
    resume: '', 
    apiKey: '' 
  });
  const [drafts, setDrafts] = useState([]);
  const [status, setStatus] = useState('idle');

  const handleInputChange = (e) => {
    setInputs({ ...inputs, [e.target.name]: e.target.value });
  };

  const onGenerate = async (e) => {
    e.preventDefault();
    if (!file) return alert("Please upload an Excel file.");
    
    setStatus('generating');
    const formData = new FormData();
    formData.append('excel_file', file);
    formData.append('resume_summary', inputs.resume);  // ✅ now correctly sends value
    formData.append('api_key', inputs.apiKey);

    try {
      const res = await axios.post('http://localhost:8000/generate-drafts', formData);
      setDrafts(res.data.drafts);
      setStatus('reviewing');
    } catch (err) {
      console.error("DEBUG ERROR:", err.response?.data);
      alert(`API Error: ${err.response?.data?.detail || "Check your terminal/console"}`);
      setStatus('idle');
    }
  };

  const handleEdit = (index, newText) => {
    const updated = [...drafts];
    updated[index].body = newText;
    setDrafts(updated);
  };

  const onSendAll = async () => {
    // ✅ Guard: ensure credentials are present
    if (!inputs.email || !inputs.password) {
      return alert("Please fill in your Gmail address and App Password before sending.");
    }

    setStatus('sending');
    const formData = new FormData();
    formData.append('user_email', inputs.email);
    formData.append('app_password', inputs.password);
    formData.append('emails_data', JSON.stringify(drafts));

    try {
      await axios.post('http://localhost:8000/send-final-emails', formData);
      alert("Sending initiated! Your emails will be sent one-by-one with delays to prevent spam filters.");
      setDrafts([]);
      setStatus('idle');
    } catch (err) {
      console.error(err);
      alert(`Error: ${err.response?.data?.detail || "Server Error"}`);
      setStatus('reviewing');
    }
  };

  if (status === 'reviewing' || status === 'sending') {
    return (
      <div className="cold-email-container">
        <div className="review-container">
          <h2>Review & Personalize</h2>
          <p>Review the {drafts.length} drafts generated by AI.</p>
          
          {drafts.map((draft, i) => (
            <div key={i} className="draft-card">
              <div className="draft-header">
                <strong>To:</strong> {draft.hr_email} | <strong>Company:</strong> {draft.company}
              </div>
              {/* ✅ Subject preview added */}
              <div className="draft-subject">
                <strong>Subject:</strong> Application for {draft.job_desc} - {draft.company}
              </div>
              <textarea
                value={draft.body}
                onChange={(e) => handleEdit(i, e.target.value)}
                rows={8}
                disabled={status === 'sending'}
              />
            </div>
          ))}

          <div className="button-group">
            <button className="btn-send" onClick={onSendAll} disabled={status === 'sending'}>
              {status === 'sending' ? 'Sending...' : 'Confirm & Send All'}
            </button>
            <button className="btn-cancel" onClick={() => setStatus('idle')} disabled={status === 'sending'}>
              Cancel
            </button>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="cold-email-container">
      <form className="setup-form" onSubmit={onGenerate}>
        <h2>Cold Email Automation</h2>
        
        {/* ✅ No hardcoded values — all controlled via state */}
        <div className="input-group">
          <label>Gemini API Key</label>
          <input type="password" name="apiKey" placeholder="AIza..." value={inputs.apiKey} onChange={handleInputChange} required />
        </div>

        <div className="input-row">
          <div className="input-group">
            <label>Gmail Address</label>
            <input type="email" name="email" placeholder="you@gmail.com" value={inputs.email} onChange={handleInputChange} required />
          </div>
          <div className="input-group">
            <label>Gmail App Password</label>
            <input type="password" name="password" placeholder="16-character code" value={inputs.password} onChange={handleInputChange} required />
          </div>
        </div>

        {/* ✅ value prop added — this was the 422 bug */}
        <div className="input-group">
          <label>Your Resume Summary</label>
          <textarea name="resume" placeholder="Summarize your skills..." value={inputs.resume} onChange={handleInputChange} required />
        </div>

        <div className="input-group">
          <label>HR Contact Data (Excel)</label>
          <input type="file" accept=".xlsx, .xls" onChange={(e) => setFile(e.target.files[0])} required />
          <small>Required columns: hr_name, email, JD, company</small>
        </div>

        <button className="btn-generate" type="submit" disabled={status === 'generating'}>
          {status === 'generating' ? 'Generating Drafts...' : 'Start Generation'}
        </button>
      </form>
    </div>
  );
};

export default ColdEmailForm;